[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
evm_version = 'default'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
